apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: docker-registry
  namespace: default
spec:
  interval: 1h
  url: https://helm.twun.io 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: default
spec:
  interval: 1h
  install:
    createNamespace: true
  chart:
    spec:
      chart: docker-registry
      sourceRef:
        kind: HelmRepository
        name: docker-registry
        namespace: default
      interval: 5m