{{- if .Values.gitclone.enabled }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tektoncd-catalog-git-clone
  namespace: default
spec:
  targetNamespace: default
  interval: 1h
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: tektoncd-catalog
    namespace: default
  path: {{ .Values.gitclone.path }}
  prune: true
  wait: true
  {{ end }}