apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/taylorshaulis/flux-apps
  ref:
    branch: main
---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: flux-apps
#   namespace: flux-system
# spec:
#   interval: 3m
#   install:
#     remediation:
#       retries: 5
#   chart:
#     spec:
#       chart: ./charts/flux-apps
#       sourceRef:
#         kind: GitRepository
#         name: flux-apps
#         namespace: flux-system
#       interval: 1m
#       valuesFiles:
#        - ./charts/flux-apps/values.yaml
#        - ./charts/flux-apps/simple_values.yaml
  # values:
  #   apps:
  #     - name: echoserver
  #       gitrepository:
  #         url: https://github.com/taylorshaulis/chicken.git
  #         branch: main
  #       helmrelease:
  #         namespace: default
  #         chart: charts/echoserver
  #     - name: hello
  #       helmrepository:
  #         url: https://cloudecho.github.io/charts/
  #       helmrelease:
  #         namespace: default
  #         chart: hello