apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/taylorshaulis/flux-apps
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  interval: 3m
  install:
    remediation:
      retries: 5
  chart:
    spec:
      chart: ./charts/flux-apps
      sourceRef:
        kind: GitRepository
        name: flux-apps
        namespace: flux-system
      interval: 1m
  values:
    foo: var