apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux2
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/fluxcd/flux2
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/manifests/  