apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vault
  namespace: default
spec:
  interval: 1h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: default
spec:
  targetNamespace: vault
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: default
      interval: 5m