apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tekton-operator
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/tektoncd/operator.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/chart/    
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton-operator
  namespace: default
spec:
  releaseName: tekton-operator
  targetNamespace: tekton-operator
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: tekton-operator
        namespace: flux-system
      interval: 5m
  values:
    installCRDs: true